# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demoRedioButton1.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, -10, 281, 71))
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(120, 50, 141, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButtonFirstClass = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButtonFirstClass.setObjectName("radioButtonFirstClass")
        self.verticalLayout.addWidget(self.radioButtonFirstClass)
        self.radioButtonBusinessClass = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButtonBusinessClass.setObjectName("radioButtonBusinessClass")
        self.verticalLayout.addWidget(self.radioButtonBusinessClass)
        self.radioButtonEconomyClass = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButtonEconomyClass.setObjectName("radioButtonEconomyClass")
        self.verticalLayout.addWidget(self.radioButtonEconomyClass)
        self.labelFare = QtWidgets.QLabel(Dialog)
        self.labelFare.setGeometry(QtCore.QRect(30, 250, 281, 51))
        self.labelFare.setText("")
        self.labelFare.setObjectName("labelFare")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Choose the flight type:"))
        self.radioButtonFirstClass.setText(_translate("Dialog", "first class"))
        self.radioButtonBusinessClass.setText(_translate("Dialog", "business class"))
        self.radioButtonEconomyClass.setText(_translate("Dialog", "economy class"))
