# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demoCheckBox2.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(832, 672)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(350, 20, 54, 12))
        self.label.setObjectName("label")
        self.labelAmount = QtWidgets.QLabel(Dialog)
        self.labelAmount.setGeometry(QtCore.QRect(200, 580, 371, 51))
        self.labelAmount.setText("")
        self.labelAmount.setObjectName("labelAmount")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(100, 90, 71, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(120, 320, 54, 12))
        self.label_4.setObjectName("label_4")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(220, 50, 331, 491))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBoxIceCreams = QtWidgets.QGroupBox(self.verticalLayoutWidget_3)
        self.groupBoxIceCreams.setCheckable(True)
        self.groupBoxIceCreams.setChecked(True)
        self.groupBoxIceCreams.setObjectName("groupBoxIceCreams")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBoxIceCreams)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 30, 181, 121))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBoxChoclateChips = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxChoclateChips.setObjectName("checkBoxChoclateChips")
        self.verticalLayout.addWidget(self.checkBoxChoclateChips)
        self.checkBoxCookieDough = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxCookieDough.setObjectName("checkBoxCookieDough")
        self.verticalLayout.addWidget(self.checkBoxCookieDough)
        self.checkBoxChoclateAlmond = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxChoclateAlmond.setObjectName("checkBoxChoclateAlmond")
        self.verticalLayout.addWidget(self.checkBoxChoclateAlmond)
        self.checkBoxRockyRoad = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxRockyRoad.setObjectName("checkBoxRockyRoad")
        self.verticalLayout.addWidget(self.checkBoxRockyRoad)
        self.groupBoxDrinks = QtWidgets.QGroupBox(self.groupBoxIceCreams)
        self.groupBoxDrinks.setGeometry(QtCore.QRect(0, 280, 329, 489))
        self.groupBoxDrinks.setCheckable(True)
        self.groupBoxDrinks.setChecked(True)
        self.groupBoxDrinks.setObjectName("groupBoxDrinks")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBoxDrinks)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(9, 30, 181, 121))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBoxCoffee = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBoxCoffee.setObjectName("checkBoxCoffee")
        self.verticalLayout_2.addWidget(self.checkBoxCoffee)
        self.checkBoxSoda = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBoxSoda.setObjectName("checkBoxSoda")
        self.verticalLayout_2.addWidget(self.checkBoxSoda)
        self.checkBoxTea = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBoxTea.setObjectName("checkBoxTea")
        self.verticalLayout_2.addWidget(self.checkBoxTea)
        self.verticalLayout_3.addWidget(self.groupBoxIceCreams)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "manu"))
        self.label_3.setText(_translate("Dialog", "IceCream"))
        self.label_4.setText(_translate("Dialog", "drink"))
        self.groupBoxIceCreams.setTitle(_translate("Dialog", "GroupBox"))
        self.checkBoxChoclateChips.setText(_translate("Dialog", "Mint cholate chips $4"))
        self.checkBoxCookieDough.setText(_translate("Dialog", "cookie dough $2"))
        self.checkBoxChoclateAlmond.setText(_translate("Dialog", "choclate almond $3"))
        self.checkBoxRockyRoad.setText(_translate("Dialog", "rocky road $5"))
        self.groupBoxDrinks.setTitle(_translate("Dialog", "GroupBox"))
        self.checkBoxCoffee.setText(_translate("Dialog", "coffee $2"))
        self.checkBoxSoda.setText(_translate("Dialog", "soda $3"))
        self.checkBoxTea.setText(_translate("Dialog", "tea $1"))
